[package]
authors = ["Michal Papierski", "Jehan Tremback", "Justin Kilpatrick", "Elvis Dedic"]
description = "Async endian safe web3 library"
edition = "2021"
license = "Apache-2.0"
name = "web30"
repository = "https://github.com/onomyprotocol/web30.git"
version = "0.18.3"

[dependencies]
clarity = { path = "../clarity" }
hyper = { version = "0.14", features = ["full"] }
hyper-tls = "0.5.0"
lazy_static = "1.4"
log = "0.4"
num = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio = { version = "1.4", features = ["macros", "time"] }
#u64_array_bigints = { path = "../u64_array_bigints/u64_array_bigints" }
u64_array_bigints = { git = "https://github.com/AaronKutch/u64_array_bigints.git", rev = "ed09e1da4720f10b094b16b0242373f2e5e5c7ac" }

[dev-dependencies]
env_logger = "0.9"
