name: Rust

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2
        continue-on-error: true
      - name: Build
        run: cargo build --verbose
  runs_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2
        continue-on-error: true
      - name: Run tests
        run: cargo test --verbose
  code_formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check code formatting
        run: rustup component add rustfmt && cargo fmt --all -- --check
  clippy_lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2
        continue-on-error: true
      - name: Check for Clippy lints
        run: rustup component add clippy && cargo clippy --all --all-targets --all-features -- -D warnings
